import type { Metadata } from "next";
import AuthLayoutProvider from "@/layout/auth/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const { theme, radius } = useThemeStore();
  return (

    <>
      <AuthLayoutProvider trans={null}>
        <section className="w-full flex flex-col h-screen">
          {children}
        </section>
      </AuthLayoutProvider>
    </>

  );
}
