import Providers from "@/components/providers";
import {getServerSession} from "next-auth";
import "@/assets/scss/app.scss";
import Header from "@/layouts/auth/header";
import Footer from "@/layouts/auth/footer";
import SessionProvider from "@/components/providers/session-provider";
import ThemeProvider from "@/components/providers/theme-provider";
import {Toaster} from "@/components/ui/toaster";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <SessionProvider>
            <body>
            <Header/>
            <div vaul-drawer-wrapper="">
                <main className="relative flex min-h-screen flex-col bg-background">
                    {children}
                </main>
            </div>
            {/*<Footer/>*/}
            <Toaster/>
            </body>
        </SessionProvider>
        </html>
    )
}
