import type { Metadata } from "next";
import GlobalLayoutProvider from "@/layout/global/layout";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function GlobalLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    // const { theme, radius } = useThemeStore();
    return (

        <>
            <GlobalLayoutProvider trans={null}>
                {children}
            </GlobalLayoutProvider>
        </>

    );
}
