import Providers from "@/components/providers";
import {getServerSession} from "next-auth";
import "@/assets/scss/app.scss";
import Header from "@/layouts/auth/header";
import Footer from "@/layouts/auth/footer";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {
    const session = await getServerSession();

    return (
        <html lang="en">
        <Providers session={session}>
            <body>
            <Header/>
            <div vaul-drawer-wrapper="">
                <main className="relative flex min-h-screen flex-col bg-background">
                    {children}
                </main>
            </div>
            <Footer/>
            </body>
        </Providers>
        </html>
    )
}
